cache: apt
dist: trusty
sudo: false
group: edge
language: python
python: 3.6
install:
  - pip uninstall -y numpy
  - pip install .
  - pip install pytest
jobs:
  include:
    - os: osx
      language: generic
      before_install:
        - curl -LO https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
        - bash Miniconda3-latest-MacOSX-x86_64.sh -b -p miniconda
        - export PATH="$PWD/miniconda/bin:$PATH"
        - conda config --set always_yes yes --set changeps1 no
        - conda update -q conda
        - conda create -q -n env python=3.6 numpy cython
        - source activate env
      script: pytest -v tests
    - script: pytest -v tests
    - stage: parse
      env: FRAMEWORK=ucca
    - env: FRAMEWORK=amr
    - env: FRAMEWORK=dm
    - env: FRAMEWORK=eds
    - env: FRAMEWORK=psd
before_script: # https://github.com/travis-ci/travis-ci/issues/8982#issuecomment-354357640
  - python -c "import fcntl; fcntl.fcntl(1, fcntl.F_SETFL, 0)"
script:
  - python -m tupa -t test_files/$FRAMEWORK.mrp -d test_files/$FRAMEWORK.mrp --conllu test_files/udpipe.mrp -I2
